<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Product 1',
                'slug' => 'product-1',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 2363.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Product 2',
                'slug' => 'product-2',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1124.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Product 3',
                'slug' => 'product-3',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1963.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Product 4',
                'slug' => 'product-4',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1633.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Product 5',
                'slug' => 'product-5',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1408.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Product 6',
                'slug' => 'product-6',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 888.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/product-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Laptop 1',
                'slug' => 'laptop-1',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1533.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Laptop 2',
                'slug' => 'laptop-2',
                'details' => '15 inch, 2 TB SSD, 32GB RAM',
                'price' => 2347.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 9,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-10-11 16:57:53',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Laptop 3',
                'slug' => 'laptop-3',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1524.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Laptop 4',
                'slug' => 'laptop-4',
                'details' => '15 inch, 1 TB SSD, 32GB RAM',
                'price' => 1925.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Laptop 5',
                'slug' => 'laptop-5',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1652.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Laptop 6',
                'slug' => 'laptop-6',
                'details' => '15 inch, 2 TB SSD, 32GB RAM',
                'price' => 2007.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Laptop 7',
                'slug' => 'laptop-7',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1980.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Laptop 8',
                'slug' => 'laptop-8',
                'details' => '15 inch, 3 TB SSD, 32GB RAM',
                'price' => 1699.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Laptop 9',
                'slug' => 'laptop-9',
                'details' => '13 inch, 1 TB SSD, 32GB RAM',
                'price' => 1638.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Laptop 10',
                'slug' => 'laptop-10',
                'details' => '14 inch, 1 TB SSD, 32GB RAM',
                'price' => 1502.0,
                'description' => 'Lorem 10 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-10.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Laptop 11',
                'slug' => 'laptop-11',
                'details' => '14 inch, 1 TB SSD, 32GB RAM',
                'price' => 1577.0,
                'description' => 'Lorem 11 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-11.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Laptop 12',
                'slug' => 'laptop-12',
                'details' => '15 inch, 2 TB SSD, 32GB RAM',
                'price' => 2112.0,
                'description' => 'Lorem 12 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-12.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Laptop 13',
                'slug' => 'laptop-13',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1910.0,
                'description' => 'Lorem 13 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-13.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Laptop 14',
                'slug' => 'laptop-14',
                'details' => '14 inch, 2 TB SSD, 32GB RAM',
                'price' => 1525.0,
                'description' => 'Lorem 14 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-14.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 9,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-10-06 17:29:56',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Laptop 15',
                'slug' => 'laptop-15',
                'details' => '14 inch, 2 TB SSD, 32GB RAM',
                'price' => 2435.0,
                'description' => 'Lorem 15 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-15.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Laptop 16',
                'slug' => 'laptop-16',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 1781.0,
                'description' => 'Lorem 16 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-16.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Laptop 17',
                'slug' => 'laptop-17',
                'details' => '13 inch, 3 TB SSD, 32GB RAM',
                'price' => 2346.0,
                'description' => 'Lorem 17 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-17.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Laptop 18',
                'slug' => 'laptop-18',
                'details' => '14 inch, 2 TB SSD, 32GB RAM',
                'price' => 1922.0,
                'description' => 'Lorem 18 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-18.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Laptop 19',
                'slug' => 'laptop-19',
                'details' => '13 inch, 1 TB SSD, 32GB RAM',
                'price' => 1977.0,
                'description' => 'Lorem 19 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-19.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Laptop 20',
                'slug' => 'laptop-20',
                'details' => '15 inch, 2 TB SSD, 32GB RAM',
                'price' => 2255.0,
                'description' => 'Lorem 20 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-20.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Laptop 21',
                'slug' => 'laptop-21',
                'details' => '13 inch, 1 TB SSD, 32GB RAM',
                'price' => 1647.0,
                'description' => 'Lorem 21 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-21.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Laptop 22',
                'slug' => 'laptop-22',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 2216.0,
                'description' => 'Lorem 22 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-22.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Laptop 23',
                'slug' => 'laptop-23',
                'details' => '15 inch, 2 TB SSD, 32GB RAM',
                'price' => 1613.0,
                'description' => 'Lorem 23 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-23.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Laptop 24',
                'slug' => 'laptop-24',
                'details' => '15 inch, 3 TB SSD, 32GB RAM',
                'price' => 2428.0,
                'description' => 'Lorem 24 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-24.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Laptop 25',
                'slug' => 'laptop-25',
                'details' => '13 inch, 1 TB SSD, 32GB RAM',
                'price' => 1805.0,
                'description' => 'Lorem 25 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-25.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Laptop 26',
                'slug' => 'laptop-26',
                'details' => '13 inch, 3 TB SSD, 32GB RAM',
                'price' => 1992.0,
                'description' => 'Lorem 26 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-26.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Laptop 27',
                'slug' => 'laptop-27',
                'details' => '14 inch, 1 TB SSD, 32GB RAM',
                'price' => 2030.0,
                'description' => 'Lorem 27 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-27.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Laptop 28',
                'slug' => 'laptop-28',
                'details' => '15 inch, 1 TB SSD, 32GB RAM',
                'price' => 1826.0,
                'description' => 'Lorem 28 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-28.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Laptop 29',
                'slug' => 'laptop-29',
                'details' => '13 inch, 2 TB SSD, 32GB RAM',
                'price' => 2370.0,
                'description' => 'Lorem 29 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-29.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Laptop 30',
                'slug' => 'laptop-30',
                'details' => '13 inch, 1 TB SSD, 32GB RAM',
                'price' => 2340.0,
                'description' => 'Lorem 30 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/laptop-30.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Desktop 1',
                'slug' => 'desktop-1',
                'details' => '25 inch, 2 TB SSD, 32GB RAM',
                'price' => 3775.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Desktop 2',
                'slug' => 'desktop-2',
                'details' => '27 inch, 3 TB SSD, 32GB RAM',
                'price' => 2623.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Desktop 3',
                'slug' => 'desktop-3',
                'details' => '24 inch, 1 TB SSD, 32GB RAM',
                'price' => 3939.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Desktop 4',
                'slug' => 'desktop-4',
                'details' => '24 inch, 3 TB SSD, 32GB RAM',
                'price' => 4009.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Desktop 5',
                'slug' => 'desktop-5',
                'details' => '25 inch, 3 TB SSD, 32GB RAM',
                'price' => 3246.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Desktop 6',
                'slug' => 'desktop-6',
                'details' => '24 inch, 2 TB SSD, 32GB RAM',
                'price' => 2571.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Desktop 7',
                'slug' => 'desktop-7',
                'details' => '27 inch, 2 TB SSD, 32GB RAM',
                'price' => 4150.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Desktop 8',
                'slug' => 'desktop-8',
                'details' => '24 inch, 3 TB SSD, 32GB RAM',
                'price' => 3913.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Desktop 9',
                'slug' => 'desktop-9',
                'details' => '24 inch, 3 TB SSD, 32GB RAM',
                'price' => 3249.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/desktop-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Phone 1',
                'slug' => 'phone-1',
                'details' => '64GB, 5.9 inch screen, 4GHz Quad Core',
                'price' => 1129.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Phone 2',
                'slug' => 'phone-2',
                'details' => '32GB, 5.7 inch screen, 4GHz Quad Core',
                'price' => 1069.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Phone 3',
                'slug' => 'phone-3',
                'details' => '64GB, 5.9 inch screen, 4GHz Quad Core',
                'price' => 1049.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Phone 4',
                'slug' => 'phone-4',
                'details' => '64GB, 5.9 inch screen, 4GHz Quad Core',
                'price' => 1140.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Phone 5',
                'slug' => 'phone-5',
                'details' => '16GB, 5.7 inch screen, 4GHz Quad Core',
                'price' => 842.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Phone 6',
                'slug' => 'phone-6',
                'details' => '16GB, 5.8 inch screen, 4GHz Quad Core',
                'price' => 1276.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Phone 7',
                'slug' => 'phone-7',
                'details' => '32GB, 5.8 inch screen, 4GHz Quad Core',
                'price' => 1072.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Phone 8',
                'slug' => 'phone-8',
                'details' => '64GB, 5.9 inch screen, 4GHz Quad Core',
                'price' => 1065.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Phone 9',
                'slug' => 'phone-9',
                'details' => '64GB, 5.8 inch screen, 4GHz Quad Core',
                'price' => 996.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/phone-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Tablet 1',
                'slug' => 'tablet-1',
                'details' => '64GB, 5.12 inch screen, 4GHz Quad Core',
                'price' => 1274.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Tablet 2',
                'slug' => 'tablet-2',
                'details' => '64GB, 5.11 inch screen, 4GHz Quad Core',
                'price' => 1086.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Tablet 3',
                'slug' => 'tablet-3',
                'details' => '32GB, 5.12 inch screen, 4GHz Quad Core',
                'price' => 1052.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Tablet 4',
                'slug' => 'tablet-4',
                'details' => '16GB, 5.10 inch screen, 4GHz Quad Core',
                'price' => 1196.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Tablet 5',
                'slug' => 'tablet-5',
                'details' => '16GB, 5.12 inch screen, 4GHz Quad Core',
                'price' => 1392.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Tablet 6',
                'slug' => 'tablet-6',
                'details' => '32GB, 5.11 inch screen, 4GHz Quad Core',
                'price' => 1421.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Tablet 7',
                'slug' => 'tablet-7',
                'details' => '32GB, 5.10 inch screen, 4GHz Quad Core',
                'price' => 788.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Tablet 8',
                'slug' => 'tablet-8',
                'details' => '32GB, 5.10 inch screen, 4GHz Quad Core',
                'price' => 1021.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Tablet 9',
                'slug' => 'tablet-9',
                'details' => '64GB, 5.12 inch screen, 4GHz Quad Core',
                'price' => 834.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tablet-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'TV 1',
                'slug' => 'tv-1',
                'details' => '60 inch screen, Smart TV, 4K',
                'price' => 840.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'TV 2',
                'slug' => 'tv-2',
                'details' => '46 inch screen, Smart TV, 4K',
                'price' => 1226.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 0,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'TV 3',
                'slug' => 'tv-3',
                'details' => '46 inch screen, Smart TV, 4K',
                'price' => 1309.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'TV 4',
                'slug' => 'tv-4',
                'details' => '60 inch screen, Smart TV, 4K',
                'price' => 1257.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'TV 5',
                'slug' => 'tv-5',
                'details' => '60 inch screen, Smart TV, 4K',
                'price' => 1499.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'TV 6',
                'slug' => 'tv-6',
                'details' => '50 inch screen, Smart TV, 4K',
                'price' => 946.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'TV 7',
                'slug' => 'tv-7',
                'details' => '50 inch screen, Smart TV, 4K',
                'price' => 1198.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:50',
                'updated_at' => '2021-01-09 09:32:50',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'TV 8',
                'slug' => 'tv-8',
                'details' => '46 inch screen, Smart TV, 4K',
                'price' => 901.0,
                'description' => '<p>Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!</p>',
                'image' => 'products/tv-8.jpg',
                'images' => '["products\\/January2021\\/5rmID7LUiLLPKWTUDHpt.png","products\\/January2021\\/G3OOP0AcGEpH0acMHBLb.jpg","products\\/January2021\\/WyKKK2cxZPk2POCvSSnL.jpg","products\\/January2021\\/bMpRvuOr2ba3bPu72msy.jpg","products\\/January2021\\/IK0DN63sYj7GmsEhCYUR.jpg"]',
                'featured' => 1,
                'quantity' => 3,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-10-06 17:29:56',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'TV 9',
                'slug' => 'tv-9',
                'details' => '50 inch screen, Smart TV, 4K',
                'price' => 1482.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/tv-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Camera 1',
                'slug' => 'camera-1',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1169.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Camera 2',
                'slug' => 'camera-2',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1884.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Camera 3',
                'slug' => 'camera-3',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1222.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Camera 4',
                'slug' => 'camera-4',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1707.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Camera 5',
                'slug' => 'camera-5',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 868.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Camera 6',
                'slug' => 'camera-6',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 954.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Camera 7',
                'slug' => 'camera-7',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 2395.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Camera 8',
                'slug' => 'camera-8',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1310.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Camera 9',
                'slug' => 'camera-9',
                'details' => 'Full Frame DSLR, with 18-55mm kit lens.',
                'price' => 1728.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/camera-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Appliance 1',
                'slug' => 'appliance-1',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1476.0,
                'description' => 'Lorem 1 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-1.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Appliance 2',
                'slug' => 'appliance-2',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1301.0,
                'description' => 'Lorem 2 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-2.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Appliance 3',
                'slug' => 'appliance-3',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1294.0,
                'description' => 'Lorem 3 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-3.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Appliance 4',
                'slug' => 'appliance-4',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1292.0,
                'description' => 'Lorem 4 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-4.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Appliance 5',
                'slug' => 'appliance-5',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1448.0,
                'description' => 'Lorem 5 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-5.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Appliance 6',
                'slug' => 'appliance-6',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1396.0,
                'description' => 'Lorem 6 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-6.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Appliance 7',
                'slug' => 'appliance-7',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 987.0,
                'description' => 'Lorem 7 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-7.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Appliance 8',
                'slug' => 'appliance-8',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 1347.0,
                'description' => 'Lorem 8 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-8.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Appliance 9',
                'slug' => 'appliance-9',
                'details' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, dolorum!',
                'price' => 857.0,
                'description' => 'Lorem 9 ipsum dolor sit amet, consectetur adipisicing elit. Ipsum temporibus iusto ipsa, asperiores voluptas unde aspernatur praesentium in? Aliquam, dolore!',
                'image' => 'products/appliance-9.jpg',
                'images' => NULL,
                'featured' => 0,
                'quantity' => 10,
                'created_at' => '2021-01-09 09:32:51',
                'updated_at' => '2021-01-09 09:32:51',
            ),
            90 => 
            array (
                'id' => 92,
                'name' => 'RCA 50” 4K UHD Smart Television - RWOSU5047',
                'slug' => 'rca-4k-tv',
                'details' => 'RCA 50” 4K',
                'price' => 599.990000000000009094947017729282379150390625,
                'description' => '<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 15px; font-size: 15px; line-height: 1.5; color: #333333; font-family: TradeGothicLTW04-Roman, sans-serif;"><strong><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-family: \'TradeGothicLTW04-BoldNo.2\', sans-serif;">Product Description</span></strong><br style="box-sizing: border-box; margin: 0px; padding: 0px;" />This RCA ultra-high-definition Smart TV is perfect for streaming your favourite shows, movies and games. In stunning 4K resolution, this high-tech television has four times the number of pixels included in regular HD for uncompromising clarity. With sharp detail and vibrant colour in every scene, your thrillers, sports and action flicks look their best, even during fast-paced segments. Plus, easily access pre-loaded apps like YouTube and Netflix for fast streaming.</p>
<p style="box-sizing: border-box; margin: 0.5em 0px 0px; padding: 0px 0px 15px; font-size: 15px; line-height: 1.5; color: #333333; font-family: TradeGothicLTW04-Roman, sans-serif;"><strong><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-family: \'TradeGothicLTW04-BoldNo.2\', sans-serif;">Dimensions</span></strong><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Width:&nbsp;44.5"&nbsp;(113.0&nbsp;cm)</span><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Height:&nbsp;26.13"&nbsp;(66.4&nbsp;cm)</span><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Depth:&nbsp;3.38"&nbsp;(8.6&nbsp;cm)</span></p>
<p style="box-sizing: border-box; margin: 0.5em 0px 0px; padding: 0px 0px 15px; font-size: 15px; line-height: 1.5; color: #333333; font-family: TradeGothicLTW04-Roman, sans-serif;"><strong><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-family: \'TradeGothicLTW04-BoldNo.2\', sans-serif;">Shipping Dimensions</span></strong><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Width:&nbsp;51.75"&nbsp;(131.4&nbsp;cm)</span><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Height:&nbsp;31.25"&nbsp;(79.4&nbsp;cm)</span><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">Depth:&nbsp;7.25"&nbsp;(18.4&nbsp;cm)</span></p>
<p style="box-sizing: border-box; margin: 0.5em 0px 0px; padding: 0px; font-size: 15px; line-height: 1.5; color: #333333; font-family: TradeGothicLTW04-Roman, sans-serif;"><strong><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-family: \'TradeGothicLTW04-BoldNo.2\', sans-serif;">Weight</span></strong><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span class="dimensionsWrapper" style="box-sizing: border-box; margin: 0px 0.8em 0px 0px; padding: 0px; display: inline-block;">31.00 lbs (14.1 kg)</span></p>',
                'image' => 'products/October2021/VLO7RabR7Tc5PkMXRUvt.jpeg',
                'images' => '["products\\/October2021\\/DPM9nmYNr3PRoK7zTlmZ.jpg","products\\/October2021\\/cGZyBMvGeVIygcxBXbId.jpg","products\\/October2021\\/1dA2RdttZoaf3o4ZQT8E.jpg"]',
                'featured' => 1,
                'quantity' => 19,
                'created_at' => '2021-10-10 12:49:04',
                'updated_at' => '2021-10-10 12:55:43',
            ),
        ));
        
        
    }
}